"""Write ``temporary_files/second_rollout_two_examples_visualization.tex``.

Layout (for merging with a primary TeX that already contains the full system prompt):

- Montages: ``\\includegraphics`` uses **Overleaf** paths ``figure/<OID>.png`` (upload
  one PNG per OID into a project ``figure/`` folder).
- System text: placeholder tags ``\\{general\\_prompt\\_block\\}`` and
  ``\\{second\\_rollout\\_ablation\\_block\\}`` with **footnotes**, not full inlined rubric.
- Per example: figure, then blocks 1--6 (system\\,1, user\\,1, output\\,1, system\\,2,
  user\\,2 + embedded-JSON note, output\\,2).

  python -m viz.generate_second_rollout_two_examples_tex
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import prompts as prompts_base  # noqa: E402

from viz.generate_benchmark_visualization_tex import (  # noqa: E402
    _embed_lstlisting,
    _replace_unicode_dashes,
)

OUT_DIR = PROJECT_ROOT / "temporary_files"
BENCHMARK_TEX = OUT_DIR / "benchmark_visualization.tex"
OUT_TEX = OUT_DIR / "second_rollout_two_examples_visualization.tex"

# Wrong→wrong Gemini 2.5 Flash (none). Constraints: gold != bogus; not bogus on
# *both* trials (one bogus trial would be OK, but we pick a cleaner pattern: non-bogus
# wrong labels on both passes). Prior OIDs dropped due to montage/production issues.
GEMINI_OID = "ZTF24ablarbs"
OPUS_OID = "ZTF21abculew"

GEMINI_JSONL = PROJECT_ROOT / "results" / "second_rollout_gemini25_flash_none_n35.jsonl"
GEMINI_MANIFEST = (
    PROJECT_ROOT
    / "data_second_roll_out_ablation"
    / "metadata"
    / "gemini25_flash_none_n35.csv"
)
OPUS_JSONL = PROJECT_ROOT / "results" / "second_rollout_opus47_nothink_n35.jsonl"
OPUS_MANIFEST = (
    PROJECT_ROOT
    / "data_second_roll_out_ablation"
    / "metadata"
    / "opus47_nothink_n35.csv"
)

# Overleaf: montage PDFs/PNGs live under ``figure/`` as ``figure/<OID>.png``.
OVERLEAF_FIGURE_DIR = "figure"

SYSTEM_BLOCK1_TEX = (
    r"\noindent\texttt{\{general\_prompt\_block\}}"
    r"\footnote{Resolves to the full benchmark system rubric "
    r"(\texttt{prompts.SYSTEM\_PROMPT} in the codebase); inlined in the primary manuscript, "
    r"not repeated here.}"
)

SYSTEM_BLOCK4_TEX = (
    r"\noindent\texttt{\{second\_rollout\_ablation\_block\}}"
    r"\footnote{Resolves to \texttt{prompts.SYSTEM\_PROMPT} plus the second-trial addendum "
    r"(\texttt{SECOND\_ROLL\_ADDENDUM}) in \texttt{prompts\_second\_roll\_out\_ablation.py}; "
    r"full wording in the primary manuscript.}"
)

USER2_TAIL_NOTE = (
    "Below this metadata block, the live API user message also embeds the model's complete "
    "first-trial JSON (verbatim) under [YOUR FIRST ATTEMPT JSON --- FOR SELF-REVIEW ONLY], "
    "then asks for the second-trial JSON. "
    "Primary-manuscript placeholder for that payload: {embedded_first_attempt_json_block} "
    "(constructed by prompts_second_roll_out_ablation.build_user_prompt; "
    "archived under data_second_roll_out_ablation/priors/)."
)

TEX_PREAMBLE = r"""\documentclass[11pt]{article}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage[a4paper,margin=0.85in]{geometry}
\usepackage{graphicx}
\usepackage{xcolor}
\definecolor{hlred}{HTML}{FF0000}
\definecolor{hlyellow}{HTML}{DAA520}
\definecolor{hlgreen}{HTML}{00FF00}
\usepackage{listings}
\usepackage{titlesec}
\titleformat{\section}{\normalfont\Large\bfseries\color{teal!70!black}}{\thesection}{0.6em}{}
\titleformat{\subsection}{\normalfont\large\bfseries\color{blue!60!black}}{\thesubsection}{0.5em}{}
\usepackage{footnote}
\usepackage[hidelinks]{hyperref}
\usepackage[most]{tcolorbox}
\tcbuselibrary{breakable,listings}

\lstdefinestyle{prompttxt}{
  basicstyle=\ttfamily\footnotesize,
  breaklines=true,
  breakatwhitespace=false,
  columns=fullflexible,
  keepspaces=true,
  frame=none,
}

\lstdefinestyle{rawouttxt}{
  basicstyle=\ttfamily\footnotesize,
  breaklines=true,
  breakatwhitespace=false,
  columns=fullflexible,
  keepspaces=true,
  frame=none,
}

\tcbset{
  chatturn/.style={
    boxrule=0.4pt,
    arc=2pt,
    left=6pt,
    right=6pt,
    top=2pt,
    bottom=4pt,
    titlerule=0pt,
    toptitle=0.5mm,
    fonttitle=\sffamily\bfseries\small,
  },
  chatblue/.style={
    colback=blue!4!white,
    colframe=blue!50!black,
    colbacktitle=blue!50!black,
    coltitle=white,
  },
  chatgreen/.style={
    colback=green!4!white,
    colframe=green!45!black,
    colbacktitle=green!40!black,
    coltitle=white,
  },
  chatgrey/.style={
    colback=gray!8,
    colframe=gray!55,
    colbacktitle=gray!55,
    coltitle=white,
  },
}

\NewTColorBox{chatmsg}{O{blue} m O{}}{
  chatturn,
  chat#1,
  title={#2},
  #3
}
\makesavenoteenv{chatmsg}

\title{\textbf{Second-rollout ablation: two example OIDs (compact prompt layout)}}
\author{(generated by \texttt{viz.generate\_second\_rollout\_two\_examples\_tex})}
\date{}

\begin{document}
\maketitle
"""


def _abstract_tex(gemini_gold: str, opus_gold: str) -> str:
    return f"""\\begin{{abstract}}
Low-confidence second trial (\\texttt{{prompts\\_second\\_roll\\_out\\_ablation.py}}), $n=35$ cohort as in \\texttt{{results\\_comparison/report/20260425\\_report\\_second\\_rollout\\_ablation.md}}.
\\textbf{{Example A:}} \\texttt{{{GEMINI_OID}}} --- Gemini~2.5~Flash (\\texttt{{gemini25\\_flash\\_none}}): \\textbf{{wrong$\\,\\to\\,$wrong}} vs gold ({gemini_gold}).
\\textbf{{Example B:}} \\texttt{{{OPUS_OID}}} --- Claude Opus~4.7 \\texttt{{nothink}}: \\textbf{{wrong$\\,\\to\\,$correct}} vs gold ({opus_gold}).

\\noindent On Overleaf, include each montage as \\texttt{{figure/<OID>.png}} (file name = object ID). Full system rubrics are not inlined here; blocks 1 and 4 use short placeholder tokens with footnotes instead.
\\end{{abstract}}
"""


def _prep_listing(s: str) -> str:
    s = _replace_unicode_dashes(s or "")
    return s.replace("%", "\\%")


def _embed(s: str, style: str = "prompttxt") -> str:
    return _embed_lstlisting(_prep_listing(s), style)


def _manifest_row(csv_path: Path, oid: str) -> pd.Series:
    df = pd.read_csv(csv_path, low_memory=False)
    sub = df[df["oid"].astype(str) == oid]
    if sub.empty:
        raise KeyError(f"OID {oid} not in {csv_path}")
    return sub.iloc[0]


def _find_jsonl_row(jsonl_path: Path, oid: str) -> dict:
    for line in jsonl_path.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        rec = json.loads(line)
        if str(rec.get("oid")) == oid:
            return rec
    raise KeyError(f"OID {oid} not in {jsonl_path}")


def _first_pass_raw(prior_path: Path) -> str:
    blob = json.loads(prior_path.read_text(encoding="utf-8"))
    fp = blob.get("first_pass") or {}
    return (fp.get("raw_text") or fp.get("answer_text") or "").strip()


def _prior_path_from_row(row: pd.Series) -> Path:
    rel = row.get("ablation_prior_file")
    if rel is None or (isinstance(rel, float) and pd.isna(rel)):
        raise ValueError("missing ablation_prior_file")
    return (PROJECT_ROOT / str(rel).strip().replace("\\", "/")).resolve()


def _overleaf_montage_relpath(oid: str) -> str:
    return f"{OVERLEAF_FIGURE_DIR}/{oid}.png"


def _user_attempt1_block(oid: str, row: pd.Series) -> str:
    meta = prompts_base.manifest_row_to_metadata(row)
    return prompts_base.build_user_prompt(oid, meta)


def _user_attempt2_block(oid: str, row: pd.Series) -> str:
    body1 = _user_attempt1_block(oid, row)
    note = "\n\n---\n\n" + USER2_TAIL_NOTE
    return body1 + note


def _example_section(
    *,
    title_section: str,
    gold_note: str,
    oid: str,
    row: pd.Series,
    first_raw: str,
    second_raw: str,
    model_tex: str,
) -> str:
    rel = _overleaf_montage_relpath(oid)
    fig = (
        r"\begin{figure}[htbp]"
        "\n\\centering\n"
        rf"\includegraphics[width=0.88\textwidth]{{{rel}}}"
        "\n"
        rf"\caption{{Science--Reference--Difference montage for \texttt{{{oid}}}.}}"
        "\n\\end{figure}\n\n"
    )
    blocks: list[str] = [
        title_section,
        gold_note,
        fig,
        r"\subsection*{Block 1: System message (attempt\,1)}",
        r"\begin{chatmsg}[grey]{System — attempt 1}[breakable]",
        SYSTEM_BLOCK1_TEX,
        r"\end{chatmsg}",
        r"\subsection*{Block 2: User message (attempt\,1)}",
        r"\begin{chatmsg}[blue]{User — attempt 1}[breakable]",
        _embed(_user_attempt1_block(oid, row), "prompttxt"),
        r"\end{chatmsg}",
        rf"\subsection*{{Block 3: Model output (attempt\,1) --- \texttt{{{model_tex}}}}}",
        r"\begin{chatmsg}[green]{Output 1}[breakable]",
        _embed(first_raw, "rawouttxt"),
        r"\end{chatmsg}",
        r"\subsection*{Block 4: System message (attempt\,2)}",
        r"\begin{chatmsg}[grey]{System — attempt 2}[breakable]",
        SYSTEM_BLOCK4_TEX,
        r"\end{chatmsg}",
        r"\subsection*{Block 5: User message (attempt\,2)}",
        r"\begin{chatmsg}[blue]{User — attempt 2}[breakable]",
        _embed(_user_attempt2_block(oid, row), "prompttxt"),
        r"\end{chatmsg}",
        rf"\subsection*{{Block 6: Model output (attempt\,2) --- \texttt{{{model_tex}}}}}",
        r"\begin{chatmsg}[green]{Output 2}[breakable]",
        _embed(second_raw, "rawouttxt"),
        r"\end{chatmsg}",
    ]
    return "\n".join(blocks)


def _build_document() -> str:
    g_row = _manifest_row(GEMINI_MANIFEST, GEMINI_OID)
    o_row = _manifest_row(OPUS_MANIFEST, OPUS_OID)
    g_rec = _find_jsonl_row(GEMINI_JSONL, GEMINI_OID)
    o_rec = _find_jsonl_row(OPUS_JSONL, OPUS_OID)
    g_second = (g_rec.get("raw_text") or g_rec.get("answer_text") or "").strip()
    o_second = (o_rec.get("raw_text") or o_rec.get("answer_text") or "").strip()
    g_first = _first_pass_raw(_prior_path_from_row(g_row))
    o_first = _first_pass_raw(_prior_path_from_row(o_row))
    g_model = str(g_rec.get("model", "gemini-2.5-flash"))
    o_model = str(o_rec.get("model", "claude-opus-4-20250514"))
    gem_gold = str(g_row["target_class"])
    op_gold = str(o_row["target_class"])

    parts: list[str] = [
        TEX_PREAMBLE,
        _abstract_tex(gem_gold, op_gold),
        _example_section(
            title_section=rf"\section{{Example A: Gemini 2.5 Flash — wrong$\to$wrong (\texttt{{{GEMINI_OID}}})}}",
            gold_note=rf"\noindent\textit{{Gold: {gem_gold}. Paired correctness: wrong$\to$wrong.}}",
            oid=GEMINI_OID,
            row=g_row,
            first_raw=g_first,
            second_raw=g_second,
            model_tex=g_model.replace("_", r"\_"),
        ),
        "\n",
        _example_section(
            title_section=rf"\section{{Example B: Claude Opus 4.7 nothink — wrong$\to$correct (\texttt{{{OPUS_OID}}})}}",
            gold_note=rf"\noindent\textit{{Gold: {op_gold}. Paired correctness: wrong$\to$correct.}}",
            oid=OPUS_OID,
            row=o_row,
            first_raw=o_first,
            second_raw=o_second,
            model_tex=o_model.replace("_", r"\_"),
        ),
        r"\end{document}",
        "",
    ]
    return "\n".join(parts)


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    if not BENCHMARK_TEX.is_file():
        from viz import generate_benchmark_visualization_tex as gen_bench

        gen_bench.main()
    OUT_TEX.write_text(_build_document(), encoding="utf-8")
    print(f"Wrote {OUT_TEX}")
    if BENCHMARK_TEX.is_file():
        print(f"(benchmark TeX at {BENCHMARK_TEX})")


if __name__ == "__main__":
    main()
